* UNImiXlab
In data 22 Marzo 2023, presso i locali dell'Università degli studi di
Milano, i sottoscritti si sono riuniti per costituire il Gruppo
"UNImiXlab" libero Gruppo di fatto, apartitico e apolitico, con durata
illimitata nel tempo e senza scopo di lucro, autogestito da studenti
iscritti ai corsi dell'Università degli studi di Milano.

** Denominazione
È costituito il gruppo UNImiXlab, in seguito indicata semplicemente
con il termine Gruppo. Il Gruppo non ha finalità di
lucro. Gli utili o gli avanzi di gestione sono impiegati
esclusivamente per la realizzazione delle attività istituzionali e di
quelle ad esse connesse. Il Gruppo è svincolata da qualsiasi
ideologia politica o religiosa.

Il Gruppo ha sede in Milano, Via Celoria 18. Il trasferimento
della sede legale non comporta modifica statutaria, se avviene
all’interno dello stesso Comune. E’ data facoltà al Consiglio di
amministrazione di cambiare la sede legale, ove se ne ravvisi la
necessità, previa deliberazione dell’assemblea dei
soci. Il Gruppo è tenuta a comunicare tempestivamente qualsiasi
trasferimento di sede agli enti gestori di pubblici Albi o Registri
nei quali è iscritta.

Il Gruppo ha facoltà, qualora se ne ravvisi la necessità, di
istituire sedi secondarie o sezioni autonome dal punto di vista
patrimoniale, organizzativo ed economico.

** Finalità
È costituito il Gruppo UNImiXlab, con sede presso l'Università degli
Studi di Milano, avente come finalità la promozione della diffusione
della cultura della software open source, con particolare attenzione
agli aspetti di sicurezza, attraverso la realizzazione di progetti,
eventi, attività di formazione e di sensibilizzazione, nonché lo
sviluppo di relazioni con istituzioni, organizzazioni e comunità
nazionali ed internazionali operanti nel settore.

Il gruppo si propone inoltre di favorire la creazione di un network di
persone, organizzazioni ed università interessate alla promozione e
alla diffusione dei punti sopra elencati, al fine di condividere
esperienze, conoscenze e risorse, e di contribuire allo sviluppo di
una comunità informata e consapevole.

** Organi

Gli organi dell’Associazione sono:
- l’Assemblea degli associati;
- il Direttivo;
- il Presidente;
- il Vice-Presidente

** I soci
*** Composizione del Gruppo
Il numero dei soci è illimitato. Può diventare socio chiunque,
indipendentemente dalla propria appartenenza politica e religiosa,
sesso, cittadinanza, appartenenza etnica e professione. Agli aspiranti
soci sono richiesti l’accettazione dello statuto e dei regolamenti
interni.

*** Domanda di ammissione
Gli aspiranti soci devono presentare domanda al Consiglio di
ammnistrazione, menzionando il proprio nome, cognome e matricola
unitamente all’attestazione di accettare ed attenersi allo statuto, al
regolamento interno e alle deliberazioni degli organi sociali. La
domanda può essere presentata attraverso email, richiesta cartacea,
richiesta fisica, o mediante piattaforme digitali.

*** Soci
Sono Soci tutti coloro che si riconoscono nei fini del Gruppo, che
sono disposti a sostenerla per il raggiungimento degli scopi
istituzionali, che presentano domanda di ammissione alla Associazione
di cui al precedente paragrafo.

Gli Organi Sociali preposti si riservano di ammettere il socio
richiedente a seguito dell’esame della domanda di ammissione corredata
dalla documentazione richiesta.

*** Categorie di soci

I soci si dividono in:
 - Soci Amministrativi
 - Soci Ordinari
 - Soci Esterni
 - Soci Fondatori

*** Soci Amministrativi
I Soci Amministrativi sono Soci che sono entrati nel consiglio di
amministrazione dopo una votazione a favore del 70% dell'attuale
amministrazione.

La loro carica può decorrere a seguito di votazione straordinaria con
voti a favore di almeno il 70% dei membri del consiglio di
amministrazione.

*** Soci Ordinari
I Soci Ordinari sono persone fisiche, che entrano a far parte del
Gruppo, previa accettazione della loro domanda d’iscrizione da parte
degli organi preposti. I Soci Ordinari perdono la carica dopo aver
lasciato l'università.

*** Soci Esterni
I Soci Esterni sono persone fisiche che sono esterne all'Università
degli Studi di Milano ma che hanno interesse a far parte
dell'associazione.

*** Soci Fondatori
Sono Soci ordinari che hanno aiutato a fondare l'associazione e che
non perdono lo status di Socio anche dopo aver lasciato l'università.

*** Accettazione del socio
Entro trenta giorni dalla presentazione, salvo parere contrario anche
di un singolo membro del Consiglio Amministrativo, che dovrà
esprimerne i motivi, la qualifica di socio diverrà effettiva e al
nuovo socio verrà consegnata la tessera sociale.

*** Diritti del socio
I soci hanno diritto a:

- frequentare i locali del Gruppo e partecipare a tutte le
- iniziative e alle manifestazioni promosse dall’Associazione, come
- da apposito regolamento; a riunirsi in assemblea per discutere e
- votare sulle questioni riguardanti l’Associazione; ad eleggere ed
- essere eletti membri degli organismi dirigenti.

Hanno diritto di voto in Assemblea i soci che abbiano rinnovato la
tessere almeno cinque giorni prima dello svolgimento della
stessa. Tutti i soci hanno gli stessi doveri e godono degli stessi
diritti nei confronti del Gruppo.

*** Doveri del socio
Il socio è tenuto al rispetto dello statuto e del Regolamento interno,
ad osservare le delibere degli organi sociali, al rispetto delle
strutture e materiali messi a disposizione dall’associazione, nonché a
mantenere irreprensibile condotta civile e morale all’interno dei
locali del Gruppo.

*** Recesso del socio
La qualifica di socio si perde per:

- espulsione o radiazione
- dimissioni, che devono essere presentate per iscritto al Consiglio d'amministrazione

*** Espulsione
Il Consiglio di amministrazione ha la facoltà di espellere un
associato per i casi di seguito descritti:

- reiterata inosservanza delle disposizioni dello statuto, di
  eventuali regolamenti o delle deliberazioni degli organi sociali
- denigrazione del Gruppo, dei suoi organi sociali, dei suoi
  soci
- commettere o provocare gravi disordini durante le assemblee
- l’appropriazione indebita dei fondi sociali, atti, documenti od
  altro di proprietà del Gruppo
- l’arrecare in qualunque modo danni morali o materiali
  all’Associazione, ai locali ed alle attrezzature di sua
  pertinenza. In ogni caso, i danni materiali dovranno essere
  risarciti dall’autore o dagli autori

** L’Assemblea
*** Composizione
L’Assemblea, Ordinaria e Straordinaria, è l’organo deliberativo del
Gruppo. Hanno diritto a parteciparvi tutti i Soci. Hanno diritto di
voto i soci maggiorenni, purché non privati del diritto di voto. Il
diritto di voto dei soci minorenni è esercitato per mezzo del
genitore, ove questi sia a sua volta socio.

*** Competenze dell’Assemblea
Le Assemblee vengono convocate più volte all’anno nel periodo che va
dal 1 gennaio al 31 dicembre, mediate preavviso su canali telematici
predisposti.

L’Assemblea viene convocata tutte le volte che il Consiglio Direttivo
lo reputi necessario e ogni qual volta ne faccia richiesta motivata un
quinto dei soci aventi diritto di voto. L’Assemblea dovrà aver luogo
entro trenta giorni dalla data in cui viene richiesta, o entro la data
prevista in caso di assemblee programmate.

*** Convocazione dell’assemblea
La convocazione avviene mediante posta per via telematica. L’avviso di
convocazione è inviato almeno quindici giorni prima dell’Assemblea, e
indica il luogo, la data, l’ora in cui si terrà l’Assemblea stessa in
prima e in seconda convocazione, con il relativo ordine del giorno.

**  Scioglimento del Gruppo
La decisione motivata di scioglimento del Gruppo deve essere presa da
almeno i quattro quinti dei soci aventi diritto al voto, in
un’Assemblea valida alla presenza della maggioranza assoluta dei
medesimi. L’Assemblea stessa decide sulla devoluzione del patrimonio
residuo, dedotte le eventuali passività, per uno o più scopi stabiliti
dal presente Statuto, e comunque per associazione con finalità
analoghe o ai fini di pubblica utilità, procedendo alla nomina di uno
o più liquidatori scegliendoli unicamente tra i soci.
